
import fastily.jwiki.core.Wiki;
import com.google.gson.stream.JsonReader;
import com.google.gson.JsonElement;
//dero
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RJ's Desktop
 */



public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGetPage = new javax.swing.JButton();
        btnTestLogin = new javax.swing.JButton();
        btnLenient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGetPage.setText("Get page");
        btnGetPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetPageActionPerformed(evt);
            }
        });

        btnTestLogin.setText("Test Login");
        btnTestLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestLoginActionPerformed(evt);
            }
        });

        btnLenient.setText("isLenient? ");
        btnLenient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLenientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLenient)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGetPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(btnTestLogin)
                        .addGap(77, 77, 77))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(btnLenient)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGetPage)
                    .addComponent(btnTestLogin))
                .addGap(46, 46, 46))
        );

        btnLenient.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void btnGetPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetPageActionPerformed
        // TODO add your handling code here:
        TestWiki();
    }//GEN-LAST:event_btnGetPageActionPerformed

    private void btnTestLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestLoginActionPerformed
        // TODO add your handling code here:
        LoginTest();
    }//GEN-LAST:event_btnTestLoginActionPerformed

    private void btnLenientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLenientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLenientActionPerformed

    
     private void TestWiki(){
         System.out.println("start");
         Wiki wiki = new Wiki("remywiki.com");
         System.out.println(wiki.getPageText("Main_Page"));
         System.out.println("test");
     }
     
     private void LoginTest(){
         Wiki wiki = new Wiki("remywiki.com");
boolean success = wiki.login("<R3Z90>", "<Zsaber6660##>");

if(success)
  System.out.printf("Login as R3Z was successful!\n"/*, wiki.conf.uname)*/);
     }
     
     
     private void Lenient(){

     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetPage;
    private javax.swing.JButton btnLenient;
    private javax.swing.JButton btnTestLogin;
    // End of variables declaration//GEN-END:variables
}
